{
 "title": "Rocket.Chat MongoDB Single Node Overview",
 "description": "Rocket.Chat MongoDB Single Node Overview",
 "tags": [
  "use1",
  "workspace"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS", "query": "prometheus" },
   {
    "name": "Replica",
    "query": {
     "query": "label_values(mongodb_up,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Health metrics for $env", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "env" },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mongodb_instance_uptime_seconds{instance=~\"$Replica\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Available Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mongodb_connections{instance=~\"$Replica\",state=\"available\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ReplicaSet Members",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (group by(member_idx) (mongodb_rs_members_state{}))"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mongodb_connections{instance=~\"$Replica\", state=\"active\"}",
     "legendFormat": "{{instance}} - {{state}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "WiredTiger Cache",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_cache_bytes_total{instance=\"$Replica\"}[5m])",
     "legendFormat": "{{instance}} - {{type}}"
    },
    {
     "expr": "mongodb_mongod_wiredtiger_cache_bytes{instance=\"$Replica\"}",
     "legendFormat": "{{instance}} - {{type}}"
    }
   ]
  },
  {
   "title": "Cache Pages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mongodb_wiredtiger_cache_pages{instance=\"$Replica\"}",
     "legendFormat": "{{instance}} - {{type}}"
    },
    {
     "expr": "mongodb_mongod_wiredtiger_cache_pages{instance=\"$Replica\"}",
     "legendFormat": "{{instance}} - {{type}}"
    }
   ]
  },
  {
   "title": "Operations queued due to locks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "mongodb_ss_globalLock_currentQueue{instance=\"$Replica\"}",
     "legendFormat": "{{instance}} - {{count_type}}"
    }
   ]
  },
  {
   "title": "Rate of Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(mongodb_network_metrics_num_requests_total{instance=\"$Replica\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Oplog write intent locks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(mongodb_ss_locks_oplog_acquireCount_r{instance=\"$Replica\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cache evicted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "rate(mongodb_mongod_wiredtiger_cache_evicted_total{instance=\"$Replica\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Oplog Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mongodb_oplog_stats_size{instance=\"$Replica\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time acquiring locks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_locks_timeAcquiringMicros{instance=\"$Replica\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "createIndex command",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(mongodb_ss_metrics_commands_createIndexes_total{instance=\"$Replica\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU cores used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{instance=~\".*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resource Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Disk IO Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Writes Completed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_disk_writes_completed_total{}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Reads Completed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_network_bytesIn{}[5m])",
     "legendFormat": "Inbount {{instance}}"
    },
    {
     "expr": "rate(mongodb_ss_network_bytesOut{}[5m])",
     "legendFormat": "Outbound {{instance}}"
    }
   ]
  },
  {
   "title": "Disk latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_disk_write_time_seconds_total{}[5m]) / rate(node_disk_writes_completed_total{}[5m])",
     "legendFormat": "READ - {{instance}}"
    },
    {
     "expr": "rate(node_disk_read_time_seconds_total{ }[5m]) / rate(node_disk_reads_completed_total{ }[5m])",
     "legendFormat": "WRITE - {{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "mongodb_memory{instance=~\"$Replica\",type=~\"resident|virtual\"}",
     "legendFormat": "{{instance}} {{type}}"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mongodb_extra_info_page_faults_total{instance=~\"$Replica\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Query Metrics for $env", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 }, "repeat": "env" },
  {
   "title": "Query Operations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{instance=~\"$Replica\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mongodb_metrics_document_total{instance=~\"$Replica\"}[5m])",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_document_total{instance=~\"$Replica\"}[5m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Document Query Executor",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mongodb_metrics_query_executor_total{instance=~\"$Replica\"}[5m])",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_query_executor_total{instance=~\"$Replica\"}[5m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Replica Set Metrics for $env", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 }, "repeat": "env" },
  {
   "title": "Member Health",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mongodb_replset_number_of_members{instance=~\"$Replica\"}",
     "legendFormat": "# members"
    },
    {
     "expr": "sum(mongodb_replset_member_health{instance=~\"$Replica\"})",
     "legendFormat": "healthy members"
    },
    {
     "expr": "mongodb_mongod_replset_number_of_members{instance=~\"$Replica\"}",
     "legendFormat": "# members"
    },
    {
     "expr": "sum(mongodb_mongod_replset_member_health{instance=~\"$env\"})",
     "legendFormat": "healthy members"
    }
   ]
  },
  {
   "title": "Member State",
   "type": "timeseries",
   "description": "See which node is currently acting as the primary, secondary, ...",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mongodb_rs_members_state{instance=~\"$Replica\"}",
     "legendFormat": "{{member_idx}} - {{member_state}}"
    }
   ]
  },
  {
   "title": "Replica Query Operations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_mongod_op_latencies_ops_total{instance=~\"$Replica\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}